In [1]:
import pandas as pd

In [3]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [4]:
var["C"]= var["A"] + var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [5]:
var["python"] = var["A"] <=3
var

   A  B   C  python
0  1  5   6    True
1  2  6   8    True
2  3  7  10    True
3  4  8  12   False