In [1]:
import pandas as pd

In [2]:
sr1= pd.Series([1,2,3,4])
sr2= pd.Series([11,21,22,23])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    21
2    22
3    23
dtype: int64

In [4]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2= pd.DataFrame({"A":[1,2,3,4],"B":[21,22,23,24]})

pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  14
0  1  21
1  2  22
2  3  23
3  4  24

In [6]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2= pd.DataFrame({"A":[1,2,3,4],"B":[21,22,23,24]})

pd.concat([d1,d2],axis=1)

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24

In [7]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2= pd.DataFrame({"A":[1,2],"B":[21,22]})

pd.concat([d1,d2],axis=1,join="inner")

   A   B  A   B
0  1  11  1  21
1  2  12  2  22

In [8]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2= pd.DataFrame({"A":[1,2],"B":[21,22]})

pd.concat([d1,d2],axis=1,keys=["d1","d2"])

  d1       d2
   A   B    A     B
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  14  NaN   NaN

In [10]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
d2= pd.DataFrame({"A":[1,2],"B":[21,22]})

pd.concat([d1,d2],keys=["d1","d2"])

      A   B
d1 0  1  11
   1  2  12
   2  3  13
   3  4  14
d2 0  1  21
   1  2  22

In [11]:
d1= pd.DataFrame({"A":[1,2,3,4]})
d2= pd.DataFrame({"A":[1,2],"B":[21,22]})

pd.concat([d1,d2],keys=["d1","d2"])

      A     B
d1 0  1   NaN
   1  2   NaN
   2  3   NaN
   3  4   NaN
d2 0  1  21.0
   1  2  22.0