In [1]:
import pandas  as pd

In [2]:
dis = {"A": [1,2,3,4,5], "S":[1,2,3,4,5], "D":[1,2,3,4,5]}
d=pd.DataFrame(dis)
print(d)
d.to_csv("Test.csv", index=False)

   A  S  D
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

In [3]:
dis = {"A": [1,2,3,4,5], "S":[1,2,3,4,5], "D":[1,2,3,4,5]}
d=pd.DataFrame(dis)
print(d)
d.to_csv("Test.csv", index=False, header=[1,2,3])   #vhange header

   A  S  D
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

###Read csv

In [4]:
csv1 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv")
csv1

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [11]:
csv2 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", nrows=10)
csv2

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
5,6,Advanced encompassing implementation,Bryan Morgan,Biography,1985,6.56,2
6,7,Open-architected exuding structure,Jacqueline Young,Romance,1927,43.63,95
7,8,Persistent local encoding,Troy Cox,Science Fiction,2019,48.99,84
8,9,Optimized interactive challenge,Colin Buckley,Fantasy,1987,14.33,70
9,10,Ergonomic national hub,Samantha Ruiz,Mystery,2015,24.63,25

In [15]:
csv3 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", usecols=["Stock"])
#use multiple column and index number to find the data of column
csv3

     Stock
0      100
1       19
2       27
3        8
4       16
..     ...
495     96
496     33
497     22
498     64
499     64

[500 rows x 1 columns]

In [16]:
csv2 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", skiprows=[0,3])
csv2

,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
0,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
1,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
2,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
3,6,Advanced encompassing implementation,Bryan Morgan,Biography,1985,6.56,2
4,7,Open-architected exuding structure,Jacqueline Young,Romance,1927,43.63,95
...,...,...,...,...,...,...,...
493,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
494,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
495,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
496,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
497,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [17]:
csv2 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", index_col="Book_ID") #use as a index 
csv2

,Title,Author,Genre,Published_Year,Price,Stock
Book_ID,,,,,,
1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...
496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [18]:
csv2 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", header=1)
csv2

,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
0,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
1,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
2,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
3,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
4,6,Advanced encompassing implementation,Bryan Morgan,Biography,1985,6.56,2
...,...,...,...,...,...,...,...
494,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
495,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
496,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
497,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
498,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [20]:
csv2 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv", names=["col","col2","col3","col4", "col5", "col6","col7"])
csv2

,col,col2,col3,col4,col5,col6,col7
0,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
1,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
2,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.8,19
3,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
4,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
...,...,...,...,...,...,...,...
496,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
497,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.1,33
498,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
499,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
500,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64