In [1]:
import pandas as pd

In [2]:
csv1 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv")
csv1

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [3]:
csv1.index

RangeIndex(start=0, stop=500, step=1)

In [4]:
csv1.columns

Index(['Book_ID', 'Title', 'Author', 'Genre', 'Published_Year', 'Price',
       'Stock'],
      dtype='object')

In [6]:
csv1.describe()

          Book_ID  Published_Year       Price       Stock
count  500.000000      500.000000  500.000000  500.000000
mean   250.500000     1959.918000   27.367440   50.112000
std    144.481833       36.271511   13.243433   29.920192
min      1.000000     1900.000000    5.070000    0.000000
25%    125.750000     1927.000000   15.390000   25.000000
50%    250.500000     1961.000000   27.300000   49.000000
75%    375.250000     1990.000000   38.510000   77.000000
max    500.000000     2023.000000   49.980000  100.000000

In [8]:
csv1.head()

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [9]:
csv1.tail()

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [11]:
csv1[4:88] #by slincing find the range of data

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
5,6,Advanced encompassing implementation,Bryan Morgan,Biography,1985,6.56,2
6,7,Open-architected exuding structure,Jacqueline Young,Romance,1927,43.63,95
7,8,Persistent local encoding,Troy Cox,Science Fiction,2019,48.99,84
8,9,Optimized interactive challenge,Colin Buckley,Fantasy,1987,14.33,70
...,...,...,...,...,...,...,...
83,84,Stand-alone 24hour interface,James Ortiz,Romance,1980,44.59,20
84,85,Enhanced impactful system engine,Bianca Matthews,Science Fiction,1939,19.43,29
85,86,Re-engineered 24/7 projection,Kathryn Williams,Non-Fiction,1948,25.51,44
86,87,Decentralized actuating analyzer,Robert Johnson,Fantasy,1986,34.84,98
87,88,Robust tangible hardware,Paul Miles,Non-Fiction,1999,40.22,32

In [12]:
csv1.index.array

<NumpyExtensionArray>
[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
 ...
 490, 491, 492, 493, 494, 495, 496, 497, 498, 499]
Length: 500, dtype: int64

In [14]:
csv1.to_numpy() #covert into array

array([[1, 'Configurable modular throughput', 'Joseph Crane', ..., 1949,
        21.34, 100],
       [2, 'Persevering reciprocal knowledge user', 'Mario Moore', ...,
        1971, 35.8, 19],
       [3, 'Streamlined coherent initiative', 'Derrick Howard', ...,
        1913, 15.75, 27],
       ...,
       [498, 'Secured 24/7 neural-net', 'Heather Marks', ..., 1975,
        10.88, 22],
       [499, 'Compatible transitional budgetary management',
        'Isaac Nelson', ..., 1905, 6.94, 64],
       [500, 'Vision-oriented zero tolerance initiative',
        'David Hatfield', ..., 1921, 15.94, 64]],
      shape=(500, 7), dtype=object)

In [22]:
csv1.sort_index(axis=0, ascending= False)

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
...,...,...,...,...,...,...,...
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100

In [24]:
csv1.loc[0,"Author"]="Robin"   #change data value
csv1

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Robin,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [26]:
csv1.loc[[2,3],["Title", "Author"]]

                             Title               Author
2  Streamlined coherent initiative       Derrick Howard
3      Customizable 24hour product  Christopher Andrews

In [27]:
csv1.iloc[0,1]

'Configurable modular throughput'