In [1]:
import pandas as pd

In [2]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"C":[10,20,30,40],"D":[11,12,33,44]})
var1.join(var2)

   A   B   C   D
0  1  11  10  11
1  2  12  20  12
2  3  13  30  33
3  4  14  40  44

In [6]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var1.join(var2)

   A   B     C     D
a  1  11  10.0  11.0
b  2  12  20.0  12.0
c  3  13  30.0  33.0
d  4  14   NaN   NaN

In [8]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var2.join(var1)

    C   D  A   B
a  10  11  1  11
b  20  12  2  12
c  30  33  3  13

In [9]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var2.join(var1, how="left")

    C   D  A   B
a  10  11  1  11
b  20  12  2  12
c  30  33  3  13

In [10]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var2.join(var1, how="outer")

      C     D  A   B
a  10.0  11.0  1  11
b  20.0  12.0  2  12
c  30.0  33.0  3  13
d   NaN   NaN  4  14

In [12]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var2.join(var1, how="inner")

    C   D  A   B
a  10  11  1  11
b  20  12  2  12
c  30  33  3  13

In [17]:
ar1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
var2= pd.DataFrame({"C":[10,20,30],"D":[11,12,33]}, index=["a","b","c"])
var2.join(var1, how="inner", lsuffix="_12", rsuffix="_123")

    C   D  A   B
a  10  11  1  11
b  20  12  2  12
c  30  33  3  13