In [1]:
import pandas as pd

In [2]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,4], "C":[21,21,22,23]})

pd.merge(var1,var2, on = "A")

   A   B   C
0  1  11  21
1  2  12  21
2  3  13  22
3  4  14  23

In [4]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,5], "C":[21,21,22,23]})

pd.merge(var1,var2, on = "A")

   A   B   C
0  1  11  21
1  2  12  21
2  3  13  22

In [5]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,5], "C":[21,21,22,23]})

pd.merge(var1,var2, how="left")

   A   B     C
0  1  11  21.0
1  2  12  21.0
2  3  13  22.0
3  4  14   NaN

In [7]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,5], "C":[21,21,22,23]})

pd.merge(var1,var2, "right")

   A     B   C
0  1  11.0  21
1  2  12.0  21
2  3  13.0  22
3  5   NaN  23

In [8]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,5], "C":[21,21,22,23]})

pd.merge(var1,var2, left_index=True, right_index=True)

   A_x   B  A_y   C
0    1  11    1  21
1    2  12    2  21
2    3  13    3  22
3    4  14    5  23

In [9]:
var1= pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]})
var2= pd.DataFrame({"A":[1,2,3,5], "C":[21,21,22,23]})

pd.merge(var1,var2, left_index=True, right_index=True, suffixes=("name", "python"))

   Aname   B  Apython   C
0      1  11        1  21
1      2  12        2  21
2      3  13        3  22
3      4  14        5  23