In [5]:
import pandas as pd

In [6]:
csv1 = pd.read_csv("C:\\Users\\Ranjan Kumar\\Desktop\\All Excel Practice Files\\Books.csv")
csv1

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [8]:
csv1.replace(to_replace="Joseph Crane" , value= "robin")

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,robin,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64

In [12]:
csv1.replace({"Title": '[Configurable mudular throughout]'}, "Robin", regex= True)

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,RobinRobinRobinRobinRobinRobinRobinRobinRobinR...,Joseph Crane,Biography,1949,21.34,100
1,2,PRobinRobinsRobinvRobinRobinRobinRobinRobinRob...,Mario Moore,Fantasy,1971,35.80,19
2,3,SRobinRobinRobinRobinRobinRobinRobinRobinRobin...,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,RobinRobinsRobinRobinRobinRobinzRobinRobinRobi...,Christopher Andrews,Fiction,2020,43.52,8
4,5,ARobinRobinpRobinRobinvRobinRobin5RobinRobinRo...,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,DRobincRobinRobinRobinRobinRobinRobinRobinzRob...,James Adams,Science Fiction,1966,43.75,96
496,497,FRobinRobincRobinRobinRobinRobin-RobinRobinsRo...,Craig Thompson,Science Fiction,1919,24.10,33
497,498,SRobincRobinRobinRobinRobinRobin24/7RobinRobin...,Heather Marks,Non-Fiction,1975,10.88,22
498,499,RobinRobinRobinpRobinRobinRobinRobinRobinRobin...,Isaac Nelson,Biography,1905,6.94,64
499,500,VRobinsRobinRobinRobin-RobinRobinRobinRobinRob...,David Hatfield,Science Fiction,1921,15.94,64

In [13]:
csv1.replace(1,method= 'bfill')

C:\Users\Ranjan Kumar\AppData\Local\Temp\ipykernel_24708\2583328558.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv1.replace(1,method= 'bfill')

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,2,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
...,...,...,...,...,...,...,...
495,496,Decentralized radical forecast,James Adams,Science Fiction,1966,43.75,96
496,497,Function-based local installation,Craig Thompson,Science Fiction,1919,24.10,33
497,498,Secured 24/7 neural-net,Heather Marks,Non-Fiction,1975,10.88,22
498,499,Compatible transitional budgetary management,Isaac Nelson,Biography,1905,6.94,64
499,500,Vision-oriented zero tolerance initiative,David Hatfield,Science Fiction,1921,15.94,64